language: php

matrix:
  include:
    - php: 5.4
      dist: precise
    - php: 5.5
      dist: precise
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: nightly
  allow_failures:
    - php: nightly

env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1

before_script:
  - phpenv config-rm xdebug.ini
  - phpize && ./configure
  - make

script:
  - make test | tee test-output.txt && grep 'TEST SUMMARY$' test-output.txt > /dev/null ; test $? '!=' 0

after_failure:
  - for FILE in `find ./tests -name '*.diff'`; do echo echo $FILE; cat $FILE; echo; done
